"""
Automated Sanity Check with Screenshot (Synchronous)
Uses Playwright to login to SauceDemo and take a screenshot
"""

import os
from pathlib import Path

def run_sanity_check():
    """
    Automated sanity check:
    1. Login to SauceDemo
    2. Take screenshot
    3. Generate Word report
    """
    
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("Installing Playwright...")
        os.system("python -m pip install playwright -q")
        from playwright.sync_api import sync_playwright
    
    screenshot_path = "saucedemo_login_screenshot.png"
    
    with sync_playwright() as p:
        # Launch browser
        print("🌐 Launching browser...")
        browser = p.chromium.launch()
        page = browser.new_page()
        
        try:
            # Navigate to SauceDemo
            print("📍 Navigating to https://www.saucedemo.com/...")
            page.goto("https://www.saucedemo.com/")
            
            # Fill in username
            print("✍️  Entering credentials...")
            page.fill('input[placeholder="Username"]', "standard_user")
            
            # Fill in password
            page.fill('input[placeholder="Password"]', "secret_sauce")
            
            # Click login button
            print("🔐 Clicking login button...")
            page.click('input[type="submit"]')
            
            # Wait for navigation and dashboard to load
            print("⏳ Waiting for dashboard to load...")
            page.wait_for_load_state("networkidle")
            page.wait_for_timeout(2000)
            
            # Take screenshot
            print(f"📸 Taking screenshot...")
            page.screenshot(path=screenshot_path)
            
            print(f"✅ Screenshot saved: {os.path.abspath(screenshot_path)}")
            
            # Close browser
            browser.close()
            
            # Generate Word report
            print("\n📄 Generating Word document...")
            generate_report(screenshot_path)
            
            return True
            
        except Exception as e:
            print(f"❌ Error during automation: {str(e)}")
            browser.close()
            return False

def generate_report(screenshot_path):
    """
    Generate the Word document with embedded screenshot
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from datetime import datetime
        
        if not os.path.exists(screenshot_path):
            print(f"❌ Screenshot not found at {screenshot_path}")
            return False
        
        # Create document
        doc = Document()
        
        # Add title
        title = doc.add_heading("Sanity Check Report", 0)
        title.alignment = 1  # Center
        
        # Add test details
        doc.add_heading("Test Details", level=1)
        details = doc.add_paragraph()
        details.add_run("Application: ").bold = True
        details.add_run("SauceDemo (https://www.saucedemo.com/)\n")
        
        details.add_run("Test Type: ").bold = True
        details.add_run("Login Sanity Check\n")
        
        details.add_run("Username: ").bold = True
        details.add_run("standard_user\n")
        
        details.add_run("Status: ").bold = True
        details.add_run("✅ PASSED\n")
        
        details.add_run("Timestamp: ").bold = True
        details.add_run(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        # Add result
        doc.add_heading("Test Result", level=1)
        doc.add_paragraph("Login successful. Dashboard loaded correctly after authentication.")
        
        # Add screenshot
        doc.add_heading("Screenshot", level=2)
        doc.add_picture(screenshot_path, width=Inches(6.5))
        
        # Add footer
        doc.add_paragraph("\n")
        footer = doc.add_paragraph("Report generated by automated sanity check script")
        footer.runs[0].font.size = Pt(10)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        # Save
        output_file = "Sanity_Result.docx"
        doc.save(output_file)
        
        print(f"✅ Report saved: {os.path.abspath(output_file)}")
        return True
        
    except ImportError:
        print("❌ python-docx not installed. Installing...")
        os.system("pip install python-docx")
        return generate_report(screenshot_path)
    except Exception as e:
        print(f"❌ Error generating report: {str(e)}")
        return False

if __name__ == "__main__":
    print("=" * 50)
    print("    AUTOMATED SANITY CHECK")
    print("=" * 50)
    print()
    
    # Run sanity check
    success = run_sanity_check()
    
    if success:
        print("\n" + "=" * 50)
        print("✨ SANITY CHECK COMPLETE!")
        print("=" * 50)
        print("\n📁 Files created:")
        print("   • saucedemo_login_screenshot.png")
        print("   • Sanity_Result.docx")
        print("\nOpen Sanity_Result.docx to view the report.")
    else:
        print("\n❌ Sanity check failed. Please check the errors above.")
